name: "Check Names"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      head:
        description: "Commit reference at which to run tests"
        required: false
      base:
        description: "Commit reference from which to evaluate diffs"
        required: false
      flags:
        description: "Extra flags to pass to toys check-names"
        required: false

jobs:
  check-names:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        run: |
          toys check-names -v --github-event-name=${{ github.event_name }} --github-event-payload=${{ github.event_path }} ${{ github.event.inputs.flags }}
