name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.1"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.2"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.3"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.4"
            tasks: "--test-unit"
          - os: macos-latest
            ruby: "3.4"
            tasks: "--test-unit"
          - os: windows-latest
            ruby: "3.4"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.4"
            tasks: "--test-rubocop --test-yardoc --test-build"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      # Redirect all gem operations to a local, writable folder
      # Otherwise toys will break
      GEM_HOME: ${{ github.workspace }}/vendor/bundle
      GEM_PATH: ${{ github.workspace }}/vendor/bundle
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Configure Path
        run: echo "$GEM_HOME/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        run: |
          toys ci -v --only ${{ matrix.tasks }}
