name: Regenerate
on:
  schedule:
    - cron: '23 11 * * 0'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      # 1. Setup Environment (Cross-Platform)
      # We force 'bash' so we can use standard linux syntax on Windows too.
      - name: Setup Gem Environment
        shell: bash
        run: |
          # Use the safe runner temp dir
          GEM_DIR="$RUNNER_TEMP/gem_home"

          # Export for future steps
          echo "GEM_HOME=$GEM_DIR" >> $GITHUB_ENV
          echo "GEM_PATH=$GEM_DIR" >> $GITHUB_ENV

          # Add bin to PATH so 'toys' would work
          echo "$GEM_DIR/bin" >> $GITHUB_PATH
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.1"
          bundler-cache: false
      - name: Install tools
        run: "gem install --no-document toys"
      - name: execute
        run: |
          toys regen -v --fork ${GITHUB_EVENT_INPUTS_ARGS}
        env:
          GITHUB_EVENT_INPUTS_ARGS: ${{ github.event.inputs.args }}
