name: Regenerate
on:
  schedule:
    - cron: '23 11 * * 0'
  workflow_dispatch:
    inputs:
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      # Redirect all gem operations to a local, writable folder
      # Otherwise toys will break
      GEM_HOME: ${{ github.workspace }}/vendor/bundle
      GEM_PATH: ${{ github.workspace }}/vendor/bundle
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Install Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Configure Path
        run: echo "$GEM_HOME/bin" >> $GITHUB_PATH
      - name: Install tools
        run: "gem install --no-document toys"
      - name: execute
        run: |
          toys regen -v --fork ${{ github.event.inputs.args }}
